// File: tools/images/imageProcessor.ts

/**
 * Image download and storage logic
 *
 * Downloads generated images from URLs and saves them to disk
 */

import { existsSync } from "fs";
import * as fs from "fs/promises";
import * as path from "path";
import { log as LogNS, assertions } from "@pure/svelte/utils";

const log = LogNS.log;

/**
 * Downloads an image from a URL and saves it to the configured directory
 *
 * @param imageUrl - URL of the generated image (from fal.ai)
 * @param filename - Filename to save as (generated by promptBuilder)
 * @param config - Configuration with image_directory
 * @returns Absolute filepath of the saved image
 */
export async function downloadAndSaveImage(
  imageUrl: string,
  filename: string,
  dir: string,
  dryRun = false
): Promise<string> {
  assertions.assertDefined(imageUrl, "imageUrl");
  assertions.assertDefined(filename, "filename");
  assertions.assertDefined(dir, "dir");

  log.info(`  ├─ Downloading image...`);

  try {
    // Ensure directory exists
    if (!existsSync(dir)) {
      log.info(`  │  Creating directory: ${dir}`);
      await fs.mkdir(dir, { recursive: true });
    }

    // Download image
    const filePath = path.join(dir, filename);
    if (!dryRun) {
      const response = await fetch(imageUrl);

      if (!response.ok) {
        throw new Error(`Failed to download image: HTTP ${response.status}`);
      }

      const arrayBuffer = await response.arrayBuffer();
      const buffer = Buffer.from(arrayBuffer);

      // Save to disk
      await fs.writeFile(filePath, buffer);

      const sizeKB = (buffer.length / 1024).toFixed(1);
      log.info(`  ├─ Saved to: ${filePath} (${sizeKB} KB)`);
    }

    return filePath;

  } catch (error: any) {
    log.error(`  ✗ Download error: ${error.message || String(error)}`);
    throw new Error(`Failed to download/save image: ${error.message}`);
  }
}

/**
 * Verifies that the image directory is writable
 *
 * Should be called before starting batch generation
 */
export async function verifyImageDirectory(directory: string): Promise<void> {
  try {
    // Create directory if it doesn't exist
    if (!existsSync(directory)) {
      log.info(`Creating image directory: ${directory}`);
      await fs.mkdir(directory, { recursive: true });
    }

    // Test write permissions
    const testFile = path.join(directory, ".test_write_permission");
    await fs.writeFile(testFile, "test");
    await fs.unlink(testFile);

    log.info(`✓ Image directory is writable: ${directory}`);
  } catch (error: any) {
    throw new Error(
      `Image directory is not writable: ${directory}\n` +
      `Error: ${error.message}\n` +
      `Please check directory permissions.`
    );
  }
}
